baseURL: "https://leolb69.github.io/ttteamboss/"
languageCode: en-us
title: Time Trial
theme: hugo-theme-stack
paginate: 24

taxonomies:
  category: categories
  player: players
  tag: tags

params:
  sidebar: 
    avatar:
      enabled: true
      local: true
      src: img/boss.webp
  cover:
      linkFullImages: true

menu:
  main:
    - identifier: categories
      name: Speed
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tracks
      url: /tags/
      weight: 30
    - identifier: players
      name: Players
      url: /players/
      weight: 40
    - widget:
       homepage:
        - type: search
